### ISSUE TITLE
Order tags by name

### ISSUE THREAD

**Issue by iymeko** [iymeko/strategitica#57]
Because they should be, I think. Right now it seems like they come out of the API either ordered by date created or maybe by ID.

**Comment by citrusella** [comment]
Looking at what mine look like on Strategitica, they appear to be ordered in the following way, in order:

- Group plan tags (I only have one so there's no specific order here but I'd imagine it'd follow the logic the other two do)
- Personal tags (non-group, non-challenge), ordered in the way I organized them specifically on Habitica
- Challenge tags, ordered in the way they're organized on Habitica (which is chronological for me because I don't move them but doesn't HAVE to be)

The only exception is that one challenge tag that had been converted to a personal tag (because the challenge ended) was among the challenge tags on Strategitica still until I went in and made an edit to my tag list that probably saved the new order (I'd imagine this is probably an issue on Habitica's end with the tag getting visually moved as it's not a challenge tag any longer but not moved in the saved order).

**Comment by iymeko** [comment]
Moved to https://github.com/strategitica/strategitica/issues/26
